.publish:
  image: registry.gitlab.com/libvirt/libvirt/ci-almalinux-9:latest
  script:
    - ./build-wiki.sh
    - mv build public
  artifacts:
    paths:
      - public

# This job creates artifacts which can be browsed without making live
web:
  extends: .publish
  rules:
    # Only run if it is a merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    # Or a or a forced pipeline on non-default branch
    - if: '$CI_PIPELINE_SOURCE =~ /(push|scheduled|web)/ && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $RUN_PIPELINE == "1"'
      when: on_success
    - when: never

# This job creates artifacts and publishes them to the live site
pages:
  extends: .publish
  rules:
    # We can publish the website from pushes to the main branch only
    - if: '$CI_PIPELINE_SOURCE =~ /(push|scheduled|web)/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - when: never
