# Check that all commits are signed-off for the DCO.
# Skip on "libvirt" namespace, since we only need to run
# this test on developer's personal forks from which
# merge requests are submitted
check-dco:
  image: registry.gitlab.com/libvirt/libvirt-ci/check-dco:master
  script:
    - /check-dco
  except:
    variables:
      - $CI_PROJECT_NAMESPACE == 'libvirt'

.publish:
  image: registry.gitlab.com/libvirt/libvirt/ci-almalinux-8:latest
  script:
    - ./build-wiki.sh
    - mv build public
  artifacts:
    paths:
      - public

# This job creates artifacts which can be browsed without making live
web:
  extends: .publish
  rules:
    # Only run if it is a merge request, or a forced pipeline
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $RUN_PIPELINE == "1"'
      when: on_success
    - when: never

# This job creates artifacts and publishes them to the live site
pages:
  extends: .publish
  rules:
    # We can publish the website from pushes to the main branch only
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - when: never
